apiVersion: v1
kind: Secret
metadata:
  name: jap-shop-api-gateway-service-secret
  namespace: dev
type: Opaque
data:
  # Base64 encoded DATABASE_URL
  # To encode: echo -n "your-database-url" | base64
  DATABASE_URL: cHJpc21hK3Bvc3RncmVzOi8vYWNjZWxlcmF0ZS5wcmlzbWEtZGF0YS5uZXQvP2FwaV9rZXk9ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhjR2xmYTJWNUlqb2lNREZLV0RCTFN6WTBSMXBLUlVSS01FMHdOVVl5UVZJeE1USWlMQ0owWlc1aGJuUmZhV1FpT2lKbE9UTTVaR0ZqTlRSaU16UTJNV1prWlRjNU1qRXpPVGxsTWpKa05EZG1ZVEF6WldNM05XRTROREZqTWpjeVlqZGhPV0ZrUVRGbE1qZ3dZalJoT1dFeklpd2lhVzUwWlhKdVlXeGZjMlZqY21WMElqb2labVF4T0dSa05Ua3RPREZoTmkwME5qbGpMVGd4TkRrdFpqQTNNbUkyWmpkaU1HUXlJbjAuMU5SeG9mV1A4ak05Z1BycmZnazZ6X3JESFdJLTRlWG9lQjNNYTUybzZzTQ==
