apiVersion: v1
kind: Service
metadata:
  name: jap-shop-api-gateway-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: jap-shop-api-gateway-service
  ports:
    - port: 4001
      targetPort: 4001